name = "MJN-Modpack"
author = "warudora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92b8d1bd5b542674f083936ec87a552d723f18ce8dc23d6a6cec8323af36b0a5"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
