name = "MJX Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2260d2e6a58fd31f4ce2810aadef298a193da25a4dc4931459b5b1127bf66e3c"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
