name = "MJX Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c7b0185079649fad2abd2a53aa2ab6439f4ab824a54bc461e7c7ac8038bb41f"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
